development:
  adapter: postgresql
  encoding: unicode
  database: daycare_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: daycare_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: daycare_production
  pool: 5
  username:
  password:
